// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARxk7ZCPNMynsuSpJ1Agj2Xwmyp9HXpQs',
    appId: '1:560821369265:web:c381c25c279c56b8b62590',
    messagingSenderId: '560821369265',
    projectId: 'pokedexapp-22031',
    authDomain: 'pokedexapp-22031.firebaseapp.com',
    storageBucket: 'pokedexapp-22031.firebasestorage.app',
    measurementId: 'G-C03TJJ2MWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7O48V8unKhWEoGY9djvB9hoQtpcNpTC8',
    appId: '1:560821369265:android:b13928908ddee669b62590',
    messagingSenderId: '560821369265',
    projectId: 'pokedexapp-22031',
    storageBucket: 'pokedexapp-22031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvyVxnvxZcQD0LNyLq7zaSWBAWnhKBbT8',
    appId: '1:560821369265:ios:70d59815843864c3b62590',
    messagingSenderId: '560821369265',
    projectId: 'pokedexapp-22031',
    storageBucket: 'pokedexapp-22031.firebasestorage.app',
    iosBundleId: 'com.example.pokemonFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvyVxnvxZcQD0LNyLq7zaSWBAWnhKBbT8',
    appId: '1:560821369265:ios:70d59815843864c3b62590',
    messagingSenderId: '560821369265',
    projectId: 'pokedexapp-22031',
    storageBucket: 'pokedexapp-22031.firebasestorage.app',
    iosBundleId: 'com.example.pokemonFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARxk7ZCPNMynsuSpJ1Agj2Xwmyp9HXpQs',
    appId: '1:560821369265:web:0cadd19c66a2ae22b62590',
    messagingSenderId: '560821369265',
    projectId: 'pokedexapp-22031',
    authDomain: 'pokedexapp-22031.firebaseapp.com',
    storageBucket: 'pokedexapp-22031.firebasestorage.app',
    measurementId: 'G-TFBTH0VE5P',
  );
}
